### ISSUE TITLE
could Fudge fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [jezze/fudge#65]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by jezze** [comment]
I have thought about adding fudge as a OS payload for coreboot before and yeah I think it would work (the size needed would be more like 2 floppies rather than one) but I guess most flash chips are big enough to easily hold that amount of information.

Maybe I'll give it a go some day just for the fun of it :D

**Comment by informer2016** [comment]
@jezze Thank you very much for reply! Yes, the virtual floppies of 2.88 MB size (those rare "fat floppies") are also supported there. And luckily, when you replace the bloated proprietary UEFI by this wonderful slim open source BIOS, suddenly there is a lot of free space! for me, with UEFI it was 3.5 of 4 MB taken ---> with coreboot+SeaBIOS just 1 MB taken, other 3 MB are free now, ready to be occupied with some good OS ! LZMA compression does miracles, e.g. compressed a memtest floppy from 1.44 MB to just about 45 KB - in 32 times

Wish you great 2018 :dog2: , happy life and bugless code :wink: Will be following your project, and if one day you'd make this floppy I will be amoung the first to put it inside the bare metal :smiley:

**Comment by ayan312002** [comment]
Nice!

**Comment by informer2016** [comment]
@jezze Hi there, jezze ! :wink:  Any updates regarding a possible floppy build? _(could be 2.88MB - it is supported)_ I'll be updating my coreboot in the near future and that would be a good opportunity to test your OS as a part of coreboot - I will do it if a floppy would be available
